### ISSUE TITLE
possible wrong battery reported

### ISSUE THREAD

**Issue by xuefer** [atc1441/ATC_MiThermometer#18]
HA says 100% using official firmware, while custom firmware shows minimal battery icon on LCD

**Comment by atc1441** [comment]
Hey, 

so the stock battery reporting is broken. 

The reason you see the Battery icon in the LCD is because i use it to show the current battery % in the Humidity display

Every time the Battery icon is showing the current status is viewable in the Humidity field. you can turn that of via the Web Flasher if not needed.


Also i set the 100% battery to 3.1V and not to 3.0V so you can better see how much overhang the battery still has.

**Comment by xuefer** [comment]
thanks. it's a good feature except for lacking of document. i'll keep it on despite it's blinking

**Comment by atc1441** [comment]
Good :) 

It is documented here: https://github.com/atc1441/ATC_MiThermometer#show-battery-level-in-lcd-

**Comment by xuefer** [comment]
indeed, but hard to understand
```
The battery level will be shown on the LCD every 5-6secdonds indicated by the battery symbol at the humidity display.
```

```
Will show Humidity% or Battery% flipping back and forth every 5~6 seconds, with battery symbol at bottom indicated it's battery level
```
i'm not English native though, but i do believe the meaning of "switching"/"flipping" should be emphasized

**Comment by atc1441** [comment]
Simply added both versions for now.

Not an English native myself so i dont know better :)
